# Generated by Django 5.2.9 on 2026-01-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_restructure_models"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["group", "order", "name"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="group",
            field=models.CharField(blank=True, max_length=50, verbose_name="Grupo"),
        ),
        migrations.AddField(
            model_name="category",
            name="is_essential",
            field=models.BooleanField(
                default=False,
                help_text="Despesa essencial (moradia, alimentação básica, etc)",
                verbose_name="Essencial",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Categoria padrão do sistema (não pode ser excluída)",
                verbose_name="Sistema",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="finance.category",
                verbose_name="Categoria Pai",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ai_categorized",
            field=models.BooleanField(
                default=False, verbose_name="Categorizado por IA"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ai_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Nível de confiança da categorização (0-1)",
                null=True,
                verbose_name="Confiança IA",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="agenda.event",
                verbose_name="Evento Origem",
            ),
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Poupança"),
                            ("DEBT", "Quitar Dívida"),
                            ("INVESTMENT", "Investimento"),
                            ("PURCHASE", "Compra"),
                            ("EMERGENCY", "Reserva de Emergência"),
                            ("CUSTOM", "Personalizado"),
                        ],
                        default="SAVINGS",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor Meta"
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valor Atual",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="Data Meta"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativa"),
                            ("COMPLETED", "Concluída"),
                            ("PAUSED", "Pausada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="target",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10b981", max_length=7, verbose_name="Cor"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="finance.account",
                        verbose_name="Conta Vinculada",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Metas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Observação"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="finance.goal",
                        verbose_name="Meta",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goal_contributions",
                        to="finance.transaction",
                        verbose_name="Transação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribuição",
                "verbose_name_plural": "Contribuições",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Limite"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Semanal"),
                            ("MONTHLY", "Mensal"),
                            ("YEARLY", "Anual"),
                        ],
                        default="MONTHLY",
                        max_length=10,
                        verbose_name="Período",
                    ),
                ),
                (
                    "alert_threshold",
                    models.IntegerField(
                        default=80,
                        help_text="Percentual do orçamento para disparar alerta",
                        verbose_name="Alerta em %",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("start_date", models.DateField(verbose_name="Data Início")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="finance.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
                "ordering": ["-created_at"],
                "unique_together": {("user", "category", "period_type", "start_date")},
            },
        ),
    ]
