# Generated by Django 5.2.9 on 2026-01-02 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("parse_transaction", "Parse Transaction"),
                            ("insights", "Insights"),
                        ],
                        max_length=50,
                        verbose_name="Feature",
                    ),
                ),
                ("input_text", models.TextField(blank=True, verbose_name="Input")),
                (
                    "input_chars",
                    models.IntegerField(default=0, verbose_name="Input Chars"),
                ),
                (
                    "output_chars",
                    models.IntegerField(default=0, verbose_name="Output Chars"),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="Model")),
                ("success", models.BooleanField(default=True, verbose_name="Sucesso")),
                ("error_message", models.TextField(blank=True, verbose_name="Erro")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Uso IA",
                "verbose_name_plural": "Logs de Uso IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
