# Generated by Django 5.2.9 on 2026-01-02 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("AULA", "Aula"),
                            ("SHOW", "Show"),
                            ("FREELA", "Freela"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="Início")),
                (
                    "end_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fim"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="Local"),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor Previsto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["start_datetime"],
            },
        ),
    ]
