# Generated by Django 5.2.9 on 2026-01-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="actual_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor efetivamente recebido (se diferente do previsto)",
                max_digits=12,
                null=True,
                verbose_name="Valor Real",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="auto_create_transaction",
            field=models.BooleanField(
                default=True,
                help_text="Criar transacao automaticamente quando status mudar para PAGO",
                verbose_name="Criar Transacao Automatica",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="client_name",
            field=models.CharField(
                blank=True,
                help_text="Nome do cliente/contratante",
                max_length=200,
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="linked_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_event_link",
                to="finance.transaction",
                verbose_name="Transacao Vinculada",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Pagamento"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Observacoes"),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_datetime",
            field=models.DateTimeField(verbose_name="Inicio"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titulo"),
        ),
    ]
