# Generated by Django 5.2.8 on 2026-01-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_restructure_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], default='INFO', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='Prioridade')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('action_url', models.CharField(blank=True, help_text='URL para redirecionar ao clicar', max_length=255, verbose_name='URL de Ação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finance.budget')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finance.goal')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BUDGET_THRESHOLD', 'Orçamento em X%'), ('BUDGET_EXCEEDED', 'Orçamento estourado'), ('GOAL_PROGRESS', 'Progresso de meta'), ('GOAL_ACHIEVED', 'Meta atingida'), ('UNUSUAL_EXPENSE', 'Gasto incomum'), ('EVENT_PAYMENT', 'Pagamento de evento'), ('WEEKLY_SUMMARY', 'Resumo semanal'), ('MONTHLY_SUMMARY', 'Resumo mensal')], max_length=30, verbose_name='Tipo de Alerta')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('threshold_percentage', models.IntegerField(blank=True, help_text='Usado para alertas de orçamento (ex: 80%)', null=True, verbose_name='Percentual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='finance.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Alerta',
                'verbose_name_plural': 'Regras de Alerta',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'alert_type', 'category')},
            },
        ),
    ]
